// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "AltWrapper_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// C_ALTREP
bool C_ALTREP(SEXP x);
RcppExport SEXP _AltWrapper_C_ALTREP(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_ALTREP(x));
    return rcpp_result_gen;
END_RCPP
}
// C_get_alt_data1
SEXP C_get_alt_data1(SEXP x);
RcppExport SEXP _AltWrapper_C_get_alt_data1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_get_alt_data1(x));
    return rcpp_result_gen;
END_RCPP
}
// C_get_alt_data2
SEXP C_get_alt_data2(SEXP x);
RcppExport SEXP _AltWrapper_C_get_alt_data2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_get_alt_data2(x));
    return rcpp_result_gen;
END_RCPP
}
// C_set_alt_data1
void C_set_alt_data1(SEXP x, SEXP value);
RcppExport SEXP _AltWrapper_C_set_alt_data1(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    C_set_alt_data1(x, value);
    return R_NilValue;
END_RCPP
}
// C_set_alt_data2
void C_set_alt_data2(SEXP x, SEXP value);
RcppExport SEXP _AltWrapper_C_set_alt_data2(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    C_set_alt_data2(x, value);
    return R_NilValue;
END_RCPP
}
// C_duplicate_object
SEXP C_duplicate_object(SEXP x, SEXP shallow);
RcppExport SEXP _AltWrapper_C_duplicate_object(SEXP xSEXP, SEXP shallowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type shallow(shallowSEXP);
    rcpp_result_gen = Rcpp::wrap(C_duplicate_object(x, shallow));
    return rcpp_result_gen;
END_RCPP
}
// C_create_altrep
SEXP C_create_altrep(string class_name, SEXP x);
RcppExport SEXP _AltWrapper_C_create_altrep(SEXP class_nameSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_create_altrep(class_name, x));
    return rcpp_result_gen;
END_RCPP
}
// C_set_altrep_class
void C_set_altrep_class(string class_name, string type);
RcppExport SEXP _AltWrapper_C_set_altrep_class(SEXP class_nameSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< string >::type type(typeSEXP);
    C_set_altrep_class(class_name, type);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_inspect_method
void C_set_altrep_inspect_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_inspect_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_inspect_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_length_method
void C_set_altrep_length_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_length_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_length_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_duplicate_method
void C_set_altrep_duplicate_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_duplicate_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_duplicate_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_coerce_method
void C_set_altrep_coerce_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_coerce_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_coerce_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_serialize_method
void C_set_altrep_serialize_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_serialize_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_serialize_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_unserialize_method
void C_set_altrep_unserialize_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_unserialize_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_unserialize_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_dataptr_method
void C_set_altrep_dataptr_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_dataptr_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_dataptr_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_dataptr_or_null_method
void C_set_altrep_dataptr_or_null_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_dataptr_or_null_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_dataptr_or_null_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_subset_method
void C_set_altrep_subset_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_subset_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_subset_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_get_element_method
void C_set_altrep_get_element_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_get_element_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_get_element_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_set_altrep_region_method
void C_set_altrep_region_method(string class_name, SEXP func);
RcppExport SEXP _AltWrapper_C_set_altrep_region_method(SEXP class_nameSEXP, SEXP funcSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type class_name(class_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type func(funcSEXP);
    C_set_altrep_region_method(class_name, func);
    return R_NilValue;
END_RCPP
}
// C_check_altrep_method
void C_check_altrep_method();
RcppExport SEXP _AltWrapper_C_check_altrep_method() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    C_check_altrep_method();
    return R_NilValue;
END_RCPP
}
// C_test1
SEXP C_test1(SEXP f, SEXP x, SEXP env);
RcppExport SEXP _AltWrapper_C_test1(SEXP fSEXP, SEXP xSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type f(fSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type env(envSEXP);
    rcpp_result_gen = Rcpp::wrap(C_test1(f, x, env));
    return rcpp_result_gen;
END_RCPP
}
// C_test2
SEXP C_test2(SEXP expr, SEXP env);
RcppExport SEXP _AltWrapper_C_test2(SEXP exprSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< SEXP >::type env(envSEXP);
    rcpp_result_gen = Rcpp::wrap(C_test2(expr, env));
    return rcpp_result_gen;
END_RCPP
}
// C_setFunc
void C_setFunc(SEXP f);
RcppExport SEXP _AltWrapper_C_setFunc(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type f(fSEXP);
    C_setFunc(f);
    return R_NilValue;
END_RCPP
}
// C_test3
SEXP C_test3(SEXP x);
RcppExport SEXP _AltWrapper_C_test3(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_test3(x));
    return rcpp_result_gen;
END_RCPP
}
// I_know_it_is_not_correct
void I_know_it_is_not_correct(SEXP x, SEXP attrName);
RcppExport SEXP _AltWrapper_I_know_it_is_not_correct(SEXP xSEXP, SEXP attrNameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type attrName(attrNameSEXP);
    I_know_it_is_not_correct(x, attrName);
    return R_NilValue;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _AltWrapper_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AltWrapper_C_ALTREP", (DL_FUNC) &_AltWrapper_C_ALTREP, 1},
    {"_AltWrapper_C_get_alt_data1", (DL_FUNC) &_AltWrapper_C_get_alt_data1, 1},
    {"_AltWrapper_C_get_alt_data2", (DL_FUNC) &_AltWrapper_C_get_alt_data2, 1},
    {"_AltWrapper_C_set_alt_data1", (DL_FUNC) &_AltWrapper_C_set_alt_data1, 2},
    {"_AltWrapper_C_set_alt_data2", (DL_FUNC) &_AltWrapper_C_set_alt_data2, 2},
    {"_AltWrapper_C_duplicate_object", (DL_FUNC) &_AltWrapper_C_duplicate_object, 2},
    {"_AltWrapper_C_create_altrep", (DL_FUNC) &_AltWrapper_C_create_altrep, 2},
    {"_AltWrapper_C_set_altrep_class", (DL_FUNC) &_AltWrapper_C_set_altrep_class, 2},
    {"_AltWrapper_C_set_altrep_inspect_method", (DL_FUNC) &_AltWrapper_C_set_altrep_inspect_method, 2},
    {"_AltWrapper_C_set_altrep_length_method", (DL_FUNC) &_AltWrapper_C_set_altrep_length_method, 2},
    {"_AltWrapper_C_set_altrep_duplicate_method", (DL_FUNC) &_AltWrapper_C_set_altrep_duplicate_method, 2},
    {"_AltWrapper_C_set_altrep_coerce_method", (DL_FUNC) &_AltWrapper_C_set_altrep_coerce_method, 2},
    {"_AltWrapper_C_set_altrep_serialize_method", (DL_FUNC) &_AltWrapper_C_set_altrep_serialize_method, 2},
    {"_AltWrapper_C_set_altrep_unserialize_method", (DL_FUNC) &_AltWrapper_C_set_altrep_unserialize_method, 2},
    {"_AltWrapper_C_set_altrep_dataptr_method", (DL_FUNC) &_AltWrapper_C_set_altrep_dataptr_method, 2},
    {"_AltWrapper_C_set_altrep_dataptr_or_null_method", (DL_FUNC) &_AltWrapper_C_set_altrep_dataptr_or_null_method, 2},
    {"_AltWrapper_C_set_altrep_subset_method", (DL_FUNC) &_AltWrapper_C_set_altrep_subset_method, 2},
    {"_AltWrapper_C_set_altrep_get_element_method", (DL_FUNC) &_AltWrapper_C_set_altrep_get_element_method, 2},
    {"_AltWrapper_C_set_altrep_region_method", (DL_FUNC) &_AltWrapper_C_set_altrep_region_method, 2},
    {"_AltWrapper_C_check_altrep_method", (DL_FUNC) &_AltWrapper_C_check_altrep_method, 0},
    {"_AltWrapper_C_test1", (DL_FUNC) &_AltWrapper_C_test1, 3},
    {"_AltWrapper_C_test2", (DL_FUNC) &_AltWrapper_C_test2, 2},
    {"_AltWrapper_C_setFunc", (DL_FUNC) &_AltWrapper_C_setFunc, 1},
    {"_AltWrapper_C_test3", (DL_FUNC) &_AltWrapper_C_test3, 1},
    {"_AltWrapper_I_know_it_is_not_correct", (DL_FUNC) &_AltWrapper_I_know_it_is_not_correct, 2},
    {"_AltWrapper_rcpp_hello_world", (DL_FUNC) &_AltWrapper_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

void initialAltrepClass(DllInfo* dll);
RcppExport void R_init_AltWrapper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    initialAltrepClass(dll);
}
