# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_ALTREP <- function(x) {
    .Call(`_AltWrapper_C_ALTREP`, x)
}

C_get_alt_data1 <- function(x) {
    .Call(`_AltWrapper_C_get_alt_data1`, x)
}

C_get_alt_data2 <- function(x) {
    .Call(`_AltWrapper_C_get_alt_data2`, x)
}

C_set_alt_data1 <- function(x, value) {
    invisible(.Call(`_AltWrapper_C_set_alt_data1`, x, value))
}

C_set_alt_data2 <- function(x, value) {
    invisible(.Call(`_AltWrapper_C_set_alt_data2`, x, value))
}

C_duplicate_object <- function(x, shallow) {
    .Call(`_AltWrapper_C_duplicate_object`, x, shallow)
}

C_create_altrep <- function(class_symbol_name, x, class_type, state, attrName, attributes) {
    .Call(`_AltWrapper_C_create_altrep`, class_symbol_name, x, class_type, state, attrName, attributes)
}

C_create_internal_altrep <- function(class_type, length) {
    .Call(`_AltWrapper_C_create_internal_altrep`, class_type, length)
}

C_getName <- function(x) {
    .Call(`_AltWrapper_C_getName`, x)
}

C_duplicate <- function(x, shallow) {
    .Call(`_AltWrapper_C_duplicate`, x, shallow)
}

C_initial_package <- function(altrep_class_space, altrep_symbol_space) {
    invisible(.Call(`_AltWrapper_C_initial_package`, altrep_class_space, altrep_symbol_space))
}

C_performace_test1 <- function(a, n) {
    .Call(`_AltWrapper_C_performace_test1`, a, n)
}

C_performace_test2 <- function(env, sym, n) {
    .Call(`_AltWrapper_C_performace_test2`, env, sym, n)
}

C_test1 <- function(f, x) {
    .Call(`_AltWrapper_C_test1`, f, x)
}

C_test2 <- function(expr, env) {
    .Call(`_AltWrapper_C_test2`, expr, env)
}

C_test3 <- function(f, x) {
    .Call(`_AltWrapper_C_test3`, f, x)
}

C_test4 <- function(x) {
    invisible(.Call(`_AltWrapper_C_test4`, x))
}

rcpp_hello_world <- function() {
    .Call(`_AltWrapper_rcpp_hello_world`)
}

