# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_ALTREP <- function(x) {
    .Call(`_AltWrapper_C_ALTREP`, x)
}

C_get_alt_data1 <- function(x) {
    .Call(`_AltWrapper_C_get_alt_data1`, x)
}

C_get_alt_data2 <- function(x) {
    .Call(`_AltWrapper_C_get_alt_data2`, x)
}

C_set_alt_data1 <- function(x, value) {
    invisible(.Call(`_AltWrapper_C_set_alt_data1`, x, value))
}

C_set_alt_data2 <- function(x, value) {
    invisible(.Call(`_AltWrapper_C_set_alt_data2`, x, value))
}

C_duplicate_object <- function(x, shallow) {
    .Call(`_AltWrapper_C_duplicate_object`, x, shallow)
}

C_create_altrep <- function(class_name, x) {
    .Call(`_AltWrapper_C_create_altrep`, class_name, x)
}

C_set_altrep_class <- function(class_name, type) {
    invisible(.Call(`_AltWrapper_C_set_altrep_class`, class_name, type))
}

C_set_altrep_inspect_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_inspect_method`, class_name, func))
}

C_set_altrep_length_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_length_method`, class_name, func))
}

C_set_altrep_duplicate_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_duplicate_method`, class_name, func))
}

C_set_altrep_coerce_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_coerce_method`, class_name, func))
}

C_set_altrep_serialize_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_serialize_method`, class_name, func))
}

C_set_altrep_unserialize_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_unserialize_method`, class_name, func))
}

C_set_altrep_dataptr_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_dataptr_method`, class_name, func))
}

C_set_altrep_dataptr_or_null_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_dataptr_or_null_method`, class_name, func))
}

C_set_altrep_subset_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_subset_method`, class_name, func))
}

C_set_altrep_get_element_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_get_element_method`, class_name, func))
}

C_set_altrep_region_method <- function(class_name, func) {
    invisible(.Call(`_AltWrapper_C_set_altrep_region_method`, class_name, func))
}

C_check_altrep_method <- function() {
    invisible(.Call(`_AltWrapper_C_check_altrep_method`))
}

C_test1 <- function(f, x, env) {
    .Call(`_AltWrapper_C_test1`, f, x, env)
}

C_test2 <- function(expr, env) {
    .Call(`_AltWrapper_C_test2`, expr, env)
}

C_setFunc <- function(f) {
    invisible(.Call(`_AltWrapper_C_setFunc`, f))
}

C_test3 <- function(x) {
    .Call(`_AltWrapper_C_test3`, x)
}

I_know_it_is_not_correct <- function(x, attrName) {
    invisible(.Call(`_AltWrapper_I_know_it_is_not_correct`, x, attrName))
}

rcpp_hello_world <- function() {
    .Call(`_AltWrapper_rcpp_hello_world`)
}

